import { designTokens } from "./tokens";

const { colors } = designTokens;

export const darkTheme = {
  dark: true,
  colors: {
    primary: colors.brand.primary,
    secondary: colors.brand.secondary,
    accent: colors.brand.accent,
    surface: colors.surfaces.primaryDark,
    background: colors.background.primaryDark,
    info: colors.semantic.info,
    success: colors.semantic.success,
    warning: colors.semantic.warning,
    error: colors.semantic.error,
    "on-background": colors.text.primaryDark,
    "on-surface": colors.text.primaryDark,
    "on-primary": colors.text.inverseLight,
    "on-secondary": colors.text.inverseLight,
    "background-primary": colors.background.primaryDark,
    "background-secondary": colors.background.secondaryDark,
    "background-gradient": colors.brand.primary,
    "background-overlay": colors.background.overlayDark,
    "surface-glass": colors.surfaces.glassDark,
    "surface-primary": colors.surfaces.primaryDark,
    "surface-secondary": colors.surfaces.secondaryDark,
    "surface-elevated": colors.surfaces.elevatedDark,
    "surface-hover": colors.surfaces.hoverDark,
    "surface-active": colors.surfaces.activeDark,
    "surface-disabled": colors.surfaces.disabledDark,
    "border-subtle": colors.borders.subtleDark,
    "border-default": colors.borders.defaultDark,
    "border-focus": colors.borders.focusDark,
    "border-success": colors.semantic.success,
    "border-warning": colors.semantic.warning,
    "border-error": colors.semantic.error,
    "text-primary": colors.text.primaryDark,
    "text-secondary": colors.text.secondaryDark,
    "text-disabled": colors.text.disabledDark,
    "text-placeholder": colors.text.placeholderDark,
    "text-inverse": colors.text.inverseDark,
    "brand-primary": colors.brand.primary,
    "brand-secondary": colors.brand.secondary,
    "brand-accent": colors.brand.accent,
  },
};
