import { designTokens, tokenGroups } from "./tokens";

const { colors } = designTokens;
const { background, borders, brand, semantic, surfaces, typography } = tokenGroups;

export const darkTheme = {
  dark: true,
  colors: {
    primary: colors.brand.primary,
    secondary: colors.brand.secondary,
    accent: colors.brand.accent,
    surface: colors.surfaces.primaryDark,
    background: colors.background.primaryDark,
    info: semantic.info,
    success: semantic.success,
    warning: semantic.warning,
    error: semantic.error,
    "on-background": colors.text.primaryDark,
    "on-surface": colors.text.primaryDark,
    "on-primary": colors.text.inverseLight,
    "on-secondary": colors.text.inverseLight,
    "background-primary": background["background-primary"].dark,
    "background-secondary": background["background-secondary"].dark,
    "background-gradient": background["background-gradient"].dark,
    "background-overlay": background["background-overlay"].dark,
    "surface-glass": surfaces["surface-glass"].dark,
    "surface-primary": surfaces["surface-primary"].dark,
    "surface-secondary": surfaces["surface-secondary"].dark,
    "surface-elevated": surfaces["surface-elevated"].dark,
    "surface-hover": surfaces["surface-hover"].dark,
    "surface-active": surfaces["surface-active"].dark,
    "surface-disabled": surfaces["surface-disabled"].dark,
    "border-subtle": borders["border-subtle"].dark,
    "border-default": borders["border-default"].dark,
    "border-focus": borders["border-focus"].dark,
    "border-success": borders["border-success"],
    "border-warning": borders["border-warning"],
    "border-error": borders["border-error"],
    "text-primary": typography["text-primary"].dark,
    "text-secondary": typography["text-secondary"].dark,
    "text-disabled": typography["text-disabled"].dark,
    "text-placeholder": typography["text-placeholder"].dark,
    "text-inverse": typography["text-inverse"].dark,
    "brand-primary": brand["brand-primary"],
    "brand-secondary": brand["brand-secondary"],
    "brand-accent": brand["brand-accent"],
  },
};
