export const lightTheme = {
  dark: false,
  colors: {
    primary: "#1867c0",
    secondary: "#5cbbf6",
    accent: "#82b1ff",
    error: "#b00020",
    info: "#2196f3",
    success: "#4caf50",
    warning: "#fb8c00",
    background: "#ffffff",
    surface: "#ffffff",
    "on-background": "#000000",
    "on-surface": "#000000",
    "on-primary": "#ffffff",
    "on-secondary": "#000000",

    /* Compatibility aliases used by existing views while the light experiment is active. */
    "background-primary": "#ffffff",
    "background-secondary": "#f5f5f5",
    "background-gradient": "#ffffff",
    "background-overlay": "#eeeeee",
    "surface-glass": "#ffffff",
    "surface-primary": "#ffffff",
    "surface-secondary": "#f5f5f5",
    "surface-elevated": "#ffffff",
    "surface-hover": "#eeeeee",
    "surface-active": "#e3f2fd",
    "surface-disabled": "#eeeeee",
    "border-subtle": "#e0e0e0",
    "border-default": "#bdbdbd",
    "border-focus": "#1867c0",
    "border-success": "#4caf50",
    "border-warning": "#fb8c00",
    "border-error": "#b00020",
    "text-primary": "#212121",
    "text-secondary": "#616161",
    "text-disabled": "#9e9e9e",
    "text-placeholder": "#757575",
    "text-inverse": "#ffffff",
    "brand-primary": "#1867c0",
    "brand-secondary": "#5cbbf6",
    "brand-accent": "#82b1ff",
  },
};
