import { designTokens } from "./tokens";

const { colors } = designTokens;

export const lightTheme = {
  dark: false,
  colors: {
    primary: colors.brand.primary,
    secondary: colors.brand.secondary,
    accent: colors.brand.accent,
    surface: colors.surfaces.primaryLight,
    background: colors.background.primaryLight,
    info: colors.semantic.info,
    success: colors.semantic.success,
    warning: colors.semantic.warning,
    error: colors.semantic.error,
    "on-background": colors.text.primaryLight,
    "on-surface": colors.text.primaryLight,
    "on-primary": colors.text.inverseLight,
    "on-secondary": colors.text.inverseLight,
    "background-primary": colors.background.primaryLight,
    "background-secondary": colors.background.secondaryLight,
    "background-gradient": colors.brand.secondary,
    "background-overlay": colors.background.overlayLight,
    "surface-glass": colors.surfaces.glassLight,
    "surface-primary": colors.surfaces.primaryLight,
    "surface-secondary": colors.surfaces.secondaryLight,
    "surface-elevated": colors.surfaces.elevatedLight,
    "surface-hover": colors.surfaces.hoverLight,
    "surface-active": colors.surfaces.activeLight,
    "surface-disabled": colors.surfaces.disabledLight,
    "border-subtle": colors.borders.subtleLight,
    "border-default": colors.borders.defaultLight,
    "border-focus": colors.borders.focusLight,
    "border-success": colors.semantic.success,
    "border-warning": colors.semantic.warning,
    "border-error": colors.semantic.error,
    "text-primary": colors.text.primaryLight,
    "text-secondary": colors.text.secondaryLight,
    "text-disabled": colors.text.disabledLight,
    "text-placeholder": colors.text.placeholderLight,
    "text-inverse": colors.text.inverseLight,
    "brand-primary": colors.brand.primary,
    "brand-secondary": colors.brand.secondary,
    "brand-accent": colors.brand.accent,
  },
};
