const palette = {
  teal50: "#EFF9F7",
  teal100: "#C8EDE8",
  teal200: "#A0E0D8",
  teal300: "#72CBBF",
  teal400: "#5BBDAD",
  teal500: "#45A99A",
  teal600: "#35897C",
  teal700: "#2A6C63",
  teal800: "#1F504A",
  teal900: "#1A3A38",
  patient50: "#EDFAF4",
  patient100: "#CBF1E0",
  patient500: "#4CAF88",
  patient600: "#3A9070",
  patient700: "#2D725A",
  patient800: "#1F5442",
  psychologist50: "#F0EEFF",
  psychologist100: "#DDD9FF",
  psychologist500: "#7B6FD0",
  psychologist600: "#6358B8",
  psychologist700: "#4D44A0",
  psychologist800: "#383188",
  neutral50: "#F5FAFA",
  neutral75: "#EEF7F6",
  neutral100: "#E8F4F2",
  neutral300: "#A0C5C0",
  neutral400: "#7BADA8",
  neutral500: "#5A8480",
  white: "#FFFFFF",
  success: "#2D725A",
  warning: "#A37C08",
  error: "#D32F2F",
  info: "#4D44A0",
};

export const designTokens = {
  palette,
  colors: {
    background: {
      primaryDark: palette.teal900,
      secondaryDark: "#0E2422",
      primaryLight: palette.neutral75,
      secondaryLight: palette.teal50,
      overlayDark: palette.teal800,
      overlayLight: palette.teal100,
    },
    surfaces: {
      glassDark: palette.teal800,
      primaryDark: palette.teal900,
      secondaryDark: palette.teal800,
      elevatedDark: palette.teal700,
      hoverDark: palette.teal600,
      activeDark: palette.teal400,
      disabledDark: palette.neutral400,
      glassLight: palette.white,
      primaryLight: palette.white,
      secondaryLight: palette.teal50,
      elevatedLight: palette.white,
      hoverLight: palette.teal50,
      activeLight: palette.teal500,
      disabledLight: palette.neutral300,
    },
    borders: {
      subtleDark: palette.teal300,
      defaultDark: palette.teal200,
      focusDark: palette.teal400,
      subtleLight: palette.teal100,
      defaultLight: palette.teal200,
      focusLight: palette.teal500,
    },
    text: {
      primaryDark: palette.white,
      secondaryDark: palette.teal200,
      disabledDark: palette.neutral400,
      placeholderDark: palette.neutral300,
      inverseDark: palette.teal900,
      primaryLight: palette.teal900,
      secondaryLight: "#426460",
      disabledLight: palette.neutral300,
      placeholderLight: palette.neutral500,
      inverseLight: palette.white,
    },
    brand: {
      primary: palette.teal500,
      secondary: palette.teal600,
      accent: palette.warning,
    },
    brandLight: {
      primary: palette.teal500,
      secondary: palette.patient500,
      accent: palette.warning,
    },
    semantic: {
      success: palette.success,
      warning: palette.warning,
      error: palette.error,
      info: palette.info,
    },
  },
  shadows: {
    xs: "0 1px 2px rgba(26, 58, 56, 0.06)",
    sm: "0 4px 12px rgba(26, 58, 56, 0.08)",
    md: "0 8px 24px rgba(26, 58, 56, 0.12)",
    lg: "0 16px 40px rgba(26, 58, 56, 0.16)",
  },
  radius: {
    sm: "6px",
    md: "8px",
    lg: "12px",
    xl: "16px",
    pill: "999px",
  },
  blur: {
    sm: "8px",
    md: "14px",
    lg: "22px",
  },
  opacity: {
    low: "0.08",
    medium: "0.18",
    high: "0.34",
  },
  spacing: {
    xs: "4px",
    sm: "8px",
    md: "16px",
    lg: "24px",
    xl: "32px",
  },
};

export const tokenGroups = {
  background: {
    "background-primary": {
      dark: designTokens.colors.background.primaryDark,
      light: designTokens.colors.background.primaryLight,
    },
    "background-secondary": {
      dark: designTokens.colors.background.secondaryDark,
      light: designTokens.colors.background.secondaryLight,
    },
    "background-gradient": {
      dark: designTokens.colors.brand.primary,
      light: designTokens.colors.brand.secondary,
    },
    "background-overlay": {
      dark: designTokens.colors.background.overlayDark,
      light: designTokens.colors.background.overlayLight,
    },
  },
  surfaces: {
    "surface-glass": {
      dark: designTokens.colors.surfaces.glassDark,
      light: designTokens.colors.surfaces.glassLight,
    },
    "surface-primary": {
      dark: designTokens.colors.surfaces.primaryDark,
      light: designTokens.colors.surfaces.primaryLight,
    },
    "surface-secondary": {
      dark: designTokens.colors.surfaces.secondaryDark,
      light: designTokens.colors.surfaces.secondaryLight,
    },
    "surface-elevated": {
      dark: designTokens.colors.surfaces.elevatedDark,
      light: designTokens.colors.surfaces.elevatedLight,
    },
    "surface-hover": {
      dark: designTokens.colors.surfaces.hoverDark,
      light: designTokens.colors.surfaces.hoverLight,
    },
    "surface-active": {
      dark: designTokens.colors.surfaces.activeDark,
      light: designTokens.colors.surfaces.activeLight,
    },
    "surface-disabled": {
      dark: designTokens.colors.surfaces.disabledDark,
      light: designTokens.colors.surfaces.disabledLight,
    },
  },
  borders: {
    "border-subtle": {
      dark: designTokens.colors.borders.subtleDark,
      light: designTokens.colors.borders.subtleLight,
    },
    "border-default": {
      dark: designTokens.colors.borders.defaultDark,
      light: designTokens.colors.borders.defaultLight,
    },
    "border-focus": {
      dark: designTokens.colors.borders.focusDark,
      light: designTokens.colors.borders.focusLight,
    },
    "border-success": designTokens.colors.semantic.success,
    "border-warning": designTokens.colors.semantic.warning,
    "border-error": designTokens.colors.semantic.error,
  },
  typography: {
    "text-primary": {
      dark: designTokens.colors.text.primaryDark,
      light: designTokens.colors.text.primaryLight,
    },
    "text-secondary": {
      dark: designTokens.colors.text.secondaryDark,
      light: designTokens.colors.text.secondaryLight,
    },
    "text-disabled": {
      dark: designTokens.colors.text.disabledDark,
      light: designTokens.colors.text.disabledLight,
    },
    "text-placeholder": {
      dark: designTokens.colors.text.placeholderDark,
      light: designTokens.colors.text.placeholderLight,
    },
    "text-inverse": {
      dark: designTokens.colors.text.inverseDark,
      light: designTokens.colors.text.inverseLight,
    },
  },
  brand: {
    "brand-primary": designTokens.colors.brand.primary,
    "brand-secondary": designTokens.colors.brand.secondary,
    "brand-accent": designTokens.colors.brand.accent,
  },
  semantic: {
    success: designTokens.colors.semantic.success,
    warning: designTokens.colors.semantic.warning,
    error: designTokens.colors.semantic.error,
    info: designTokens.colors.semantic.info,
  },
  shadows: {
    "shadow-xs": designTokens.shadows.xs,
    "shadow-sm": designTokens.shadows.sm,
    "shadow-md": designTokens.shadows.md,
    "shadow-lg": designTokens.shadows.lg,
  },
  radius: {
    "radius-sm": designTokens.radius.sm,
    "radius-md": designTokens.radius.md,
    "radius-lg": designTokens.radius.lg,
    "radius-xl": designTokens.radius.xl,
    "radius-pill": designTokens.radius.pill,
  },
  blur: {
    "blur-sm": designTokens.blur.sm,
    "blur-md": designTokens.blur.md,
    "blur-lg": designTokens.blur.lg,
  },
  opacity: {
    "opacity-low": designTokens.opacity.low,
    "opacity-medium": designTokens.opacity.medium,
    "opacity-high": designTokens.opacity.high,
  },
  spacing: {
    "spacing-xs": designTokens.spacing.xs,
    "spacing-sm": designTokens.spacing.sm,
    "spacing-md": designTokens.spacing.md,
    "spacing-lg": designTokens.spacing.lg,
    "spacing-xl": designTokens.spacing.xl,
  },
};

export const designTokenCssVars = {
  "--pf-shadow-xs": designTokens.shadows.xs,
  "--pf-shadow-sm": designTokens.shadows.sm,
  "--pf-shadow-md": designTokens.shadows.md,
  "--pf-shadow-lg": designTokens.shadows.lg,
  "--pf-radius-sm": designTokens.radius.sm,
  "--pf-radius-md": designTokens.radius.md,
  "--pf-radius-lg": designTokens.radius.lg,
  "--pf-radius-xl": designTokens.radius.xl,
  "--pf-radius-pill": designTokens.radius.pill,
  "--pf-blur-sm": designTokens.blur.sm,
  "--pf-blur-md": designTokens.blur.md,
  "--pf-blur-lg": designTokens.blur.lg,
  "--pf-opacity-low": designTokens.opacity.low,
  "--pf-opacity-medium": designTokens.opacity.medium,
  "--pf-opacity-high": designTokens.opacity.high,
  "--pf-spacing-xs": designTokens.spacing.xs,
  "--pf-spacing-sm": designTokens.spacing.sm,
  "--pf-spacing-md": designTokens.spacing.md,
  "--pf-spacing-lg": designTokens.spacing.lg,
  "--pf-spacing-xl": designTokens.spacing.xl,
  "--lurems-brand-primary": palette.teal500,
  "--lurems-brand-dark": palette.teal900,
  "--lurems-brand-subtle": palette.teal50,
  "--lurems-patient-primary": palette.patient700,
  "--lurems-patient-dark": palette.patient800,
  "--lurems-patient-soft": palette.patient50,
  "--lurems-psychologist-primary": palette.psychologist700,
  "--lurems-psychologist-dark": palette.psychologist800,
  "--lurems-psychologist-soft": palette.psychologist50,
  "--pf-social-google": "168, 0, 14",
  "--pf-social-facebook": "0, 50, 199",
  "--pf-social-apple": "0, 0, 1",
};

export const therapistGradients = [
  `linear-gradient(to bottom right, ${palette.teal500}, ${palette.teal300})`,
  `linear-gradient(to bottom right, ${palette.patient500}, ${palette.teal300})`,
  `linear-gradient(to bottom right, ${palette.psychologist500}, ${palette.psychologist100})`,
  `linear-gradient(to bottom right, ${palette.teal600}, ${palette.teal200})`,
  `linear-gradient(to bottom right, ${palette.info}, ${palette.teal300})`,
  `linear-gradient(to bottom right, ${palette.success}, ${palette.teal600})`,
  `linear-gradient(to bottom right, ${palette.warning}, ${palette.teal400})`,
  `linear-gradient(to bottom right, ${palette.error}, ${palette.psychologist500})`,
  `linear-gradient(to bottom right, ${palette.teal400}, ${palette.teal100})`,
  `linear-gradient(to bottom right, ${palette.teal800}, ${palette.success})`,
];

export const defaultTherapistGradient = therapistGradients[0];
export const defaultTherapistGradientStops = {
  start: palette.teal500,
  end: palette.teal300,
};
