const palette = {
  ink: "#F4FBF8",
  inkMuted: "#C8D8D4",
  inkSoft: "#8FA6A1",
  night: "#030707",
  nightSoft: "#071112",
  forest: "#0D1C1E",
  forestSoft: "#122C2F",
  pine: "#1F4146",
  pineSoft: "#2D4A4D",
  sage: "#5F807B",
  sageSoft: "#6F8F89",
  mint: "#9EC6BD",
  mist: "#E4F0EC",
  mistDeep: "#C9DED8",
  cloud: "#F5FAF7",
  success: "#6E927B",
  warning: "#B49A66",
  error: "#C36F7F",
  info: "#4F7773",
};

export const designTokens = {
  palette,
  colors: {
    background: {
      primaryDark: palette.night,
      secondaryDark: palette.forest,
      primaryLight: palette.mist,
      secondaryLight: palette.mistDeep,
      overlayDark: palette.forestSoft,
      overlayLight: palette.cloud,
    },
    surfaces: {
      glassDark: palette.pineSoft,
      primaryDark: palette.forestSoft,
      secondaryDark: palette.pine,
      elevatedDark: palette.pineSoft,
      hoverDark: palette.sage,
      activeDark: palette.mint,
      disabledDark: palette.inkSoft,
      glassLight: palette.cloud,
      primaryLight: palette.mist,
      secondaryLight: palette.mistDeep,
      elevatedLight: palette.cloud,
      hoverLight: palette.sageSoft,
      activeLight: palette.pine,
      disabledLight: palette.inkSoft,
    },
    borders: {
      subtleDark: "#D2F4F1",
      defaultDark: "#ACE8EB",
      focusDark: palette.mint,
      subtleLight: palette.pine,
      defaultLight: palette.sage,
      focusLight: palette.pine,
    },
    text: {
      primaryDark: palette.ink,
      secondaryDark: palette.inkMuted,
      disabledDark: palette.inkSoft,
      placeholderDark: palette.inkSoft,
      inverseDark: palette.night,
      primaryLight: "#12211E",
      secondaryLight: "#415A55",
      disabledLight: "#7D908C",
      placeholderLight: "#6D827D",
      inverseLight: palette.ink,
    },
    brand: {
      primary: palette.pine,
      secondary: palette.sage,
      accent: palette.mint,
    },
    semantic: {
      success: palette.success,
      warning: palette.warning,
      error: palette.error,
      info: palette.info,
    },
  },
  shadows: {
    xs: "0 1px 2px rgba(0, 18, 20, 0.10)",
    sm: "0 10px 30px rgba(0, 18, 20, 0.18)",
    md: "0 18px 48px rgba(0, 18, 20, 0.24)",
    lg: "0 28px 76px rgba(0, 18, 20, 0.32)",
  },
  radius: {
    sm: "6px",
    md: "8px",
    lg: "12px",
    xl: "16px",
    pill: "999px",
  },
  blur: {
    sm: "8px",
    md: "14px",
    lg: "22px",
  },
  opacity: {
    low: "0.08",
    medium: "0.18",
    high: "0.34",
  },
  spacing: {
    xs: "4px",
    sm: "8px",
    md: "16px",
    lg: "24px",
    xl: "32px",
  },
};

export const designTokenCssVars = {
  "--pf-shadow-xs": designTokens.shadows.xs,
  "--pf-shadow-sm": designTokens.shadows.sm,
  "--pf-shadow-md": designTokens.shadows.md,
  "--pf-shadow-lg": designTokens.shadows.lg,
  "--pf-radius-sm": designTokens.radius.sm,
  "--pf-radius-md": designTokens.radius.md,
  "--pf-radius-lg": designTokens.radius.lg,
  "--pf-radius-xl": designTokens.radius.xl,
  "--pf-radius-pill": designTokens.radius.pill,
  "--pf-blur-sm": designTokens.blur.sm,
  "--pf-blur-md": designTokens.blur.md,
  "--pf-blur-lg": designTokens.blur.lg,
  "--pf-opacity-low": designTokens.opacity.low,
  "--pf-opacity-medium": designTokens.opacity.medium,
  "--pf-opacity-high": designTokens.opacity.high,
  "--pf-spacing-xs": designTokens.spacing.xs,
  "--pf-spacing-sm": designTokens.spacing.sm,
  "--pf-spacing-md": designTokens.spacing.md,
  "--pf-spacing-lg": designTokens.spacing.lg,
  "--pf-spacing-xl": designTokens.spacing.xl,
  "--pf-social-google": "168, 0, 14",
  "--pf-social-facebook": "0, 50, 199",
  "--pf-social-apple": "0, 0, 1",
};

export const therapistGradients = [
  `linear-gradient(to bottom right, ${palette.pine}, ${palette.sage})`,
  `linear-gradient(to bottom right, ${palette.sage}, ${palette.mint})`,
  `linear-gradient(to bottom right, ${palette.forestSoft}, ${palette.sageSoft})`,
  `linear-gradient(to bottom right, ${palette.pineSoft}, ${palette.mint})`,
  `linear-gradient(to bottom right, ${palette.info}, ${palette.sage})`,
  `linear-gradient(to bottom right, ${palette.success}, ${palette.pine})`,
  `linear-gradient(to bottom right, ${palette.warning}, ${palette.sage})`,
  `linear-gradient(to bottom right, ${palette.error}, ${palette.pineSoft})`,
  `linear-gradient(to bottom right, ${palette.sageSoft}, ${palette.mistDeep})`,
  `linear-gradient(to bottom right, ${palette.forest}, ${palette.success})`,
];

export const defaultTherapistGradient = therapistGradients[0];
export const defaultTherapistGradientStops = {
  start: palette.pine,
  end: palette.sage,
};
